@HostAddress = http://localhost:5212

### Get all categories

GET {{HostAddress}}/api/categories
Accept: application/json


### Get category by Id

GET {{HostAddress}}/api/categories/3a8958d1-6d76-447b-918c-dea633581997
Accept: application/json

### Create a new Category

POST {{HostAddress}}/api/categories/
Content-Type: application/json

{
    "name": "Cardio"
}

### Delete a category

DELETE {{HostAddress}}/api/categories/3a8958d1-6d76-447b-918c-dea633581997

### Update a category

PUT {{HostAddress}}/api/categories/3a8958d1-6d76-447b-918c-dea633581997
Content-Type: application/json

{
    "name": "Running"
}