@HostAddress = http://localhost:5212

### Get all categories

GET {{HostAddress}}/api/categories
Accept: application/json


### Get category by Id

GET {{HostAddress}}/api/categories/1d80bbc0-b48d-4c0d-9f0d-b0e2b2822880
Accept: application/json

### Create a new Category

POST {{HostAddress}}/api/categories/
Content-Type: application/json

{
    "name": "Gym"
}

### Delete a category

DELETE {{HostAddress}}/api/categories/d2fa2386-1b48-4d4b-b870-a1f50ee22c03

### Update a category

PUT {{HostAddress}}/api/categories/d2fa2386-1b48-4d4b-b870-a1f50ee22c03
Content-Type: application/json

{
    "name": "Fitness"
}