@HostAddress = http://localhost:5212

### Get all categories

GET {{HostAddress}}/api/v1/categories
Accept: application/json


### Get category by Id

GET {{HostAddress}}/api/v1/categories/4d5a9197-5238-40dc-b0b4-3d4979e62277
Accept: application/json

### Create a new Category

POST {{HostAddress}}/api/v1/categories/
Content-Type: application/json

{
    "name": "Gym"
}

### Delete a category

DELETE {{HostAddress}}/api/v1/categories/d2fa2386-1b48-4d4b-b870-a1f50ee22c03

### Update a category

PUT {{HostAddress}}/api/v1/categories/d2fa2386-1b48-4d4b-b870-a1f50ee22c03
Content-Type: application/json

{
    "name": "Fitness"
}