@HostAddress = http://localhost:5212
@Route = api/exercises

### Get all exercises

GET {{HostAddress}}/{{Route}}
Accept: application/json

### Get exercise by id

@ExerciseId = 5f337c24-7efb-45d6-92df-bc403899b533

GET {{HostAddress}}/{{Route}}/{{ExerciseId}}
Accept: application/json

### Create exercise

POST {{HostAddress}}/{{Route}}
Content-Type: application/json

{
    "categoryId": "02d2e4a7-38ae-4b46-a384-980e3dc495bf",
    "start": "2025-07-09T22:00:00",
    "end": "2025-07-09T23:00:00",
    "description": "test2"
}

### Delete exercise

@ExerciseId = 5f337c24-7efb-45d6-92df-bc403899b533

DELETE {{HostAddress}}/{{Route}}/{{ExerciseId}}
Accept: application/json

### Update exercise

@ExerciseId = 5aa2e5b9-b630-48ea-b239-5d94322b9be5

PUT {{HostAddress}}/{{Route}}/{{ExerciseId}}
Content-Type: application/json

{
    "categoryId": "02d2e4a7-38ae-4b46-a384-980e3dc495bf",
    "start": "2025-07-09T11:00:00",
    "end": "2025-07-09T12:00:00",
    "description": "test2"
}