@HostAddress = http://localhost:5212

### Get all exercises

GET {{HostAddress}}/api/v1/exercises
Accept: application/json

### Get exercise by id

GET {{HostAddress}}/api/v1/exercises/b92d836e-5ebc-41bf-9a01-13067550fcb7
Accept: application/json

### Create exercise

POST {{HostAddress}}/api/v1/exercises
Content-Type: application/json

{
    "categoryId": "1d80bbc0-b48d-4c0d-9f0d-b0e2b2822880",
    "start": "2025-07-09T23:00:00",
    "end": "2025-07-10T23:30:00",
    "description": "test123"
}

### Delete exercise

DELETE {{HostAddress}}/api/v1/exercises/b92d836e-5ebc-41bf-9a01-13067550fcb7
Accept: application/json

### Update exercise

PUT {{HostAddress}}/api/v1/exercises/b92d836e-5ebc-41bf-9a01-13067550fcb7
Content-Type: application/json

{
    "categoryId": "1d80bbc0-b48d-4c0d-9f0d-b0e2b2822880",
    "start": "2025-07-09T23:00:00",
    "end": "2025-07-09T23:30:00",
    "description": "test2"
}