@HostAddress = http://localhost:5212
@Route = api/exercises

### Get all exercises

GET {{HostAddress}}/{{Route}}
Accept: application/json

### Get exercise by id

GET {{HostAddress}}/{{Route}}/c25815e1-c51e-472c-a52e-98fbf3759863
Accept: application/json

### Create exercise

POST {{HostAddress}}/{{Route}}
Content-Type: application/json

{
    "categoryId": "1d80bbc0-b48d-4c0d-9f0d-b0e2b2822880",
    "start": "2025-07-09T23:00:00",
    "end": "2025-07-10T23:30:00",
    "description": "test2213"
}

### Delete exercise

DELETE {{HostAddress}}/{{Route}}/2bd73804-beea-4894-933d-2a6cd188cf48
Accept: application/json

### Update exercise

PUT {{HostAddress}}/{{Route}}/2bd73804-beea-4894-933d-2a6cd188cf48
Content-Type: application/json

{
    "categoryId": "1d80bbc0-b48d-4c0d-9f0d-b0e2b2822880",
    "start": "2025-07-09T23:00:00",
    "end": "2025-07-09T23:30:00",
    "description": "test2"
}